name: create-artifact

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: congestionfrr:latest
          outputs: type=docker,dest=/tmp/congestionfrr.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: congestionfrr
          path: /tmp/congestionfrr.tar
