name: Ensure Scripts Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: congestionfrr:latest
          outputs: type=docker,dest=/tmp/congestionfrr.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: congestionfrr
          path: /tmp/congestionfrr.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: congestionfrr
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/congestionfrr.tar
          docker image ls -a
      - name: Run Docker Compose
        run: docker-compose run ns3
